version: "3.1"
services:
  nginx:
    container_name: logs_nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "83:80"
    links:
      - php-fpm
    volumes:
      # - ./nginx:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./public:/var/www/html/public
    depends_on:
      -  php-fpm
    restart: always

  php-fpm:
    container_name: logs_php
    build:
      context: .
      dockerfile: php/Dockerfile
    environment:
      TZ: "Asia/Yekaterinburg"
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_IP: ${SQL_IP}
      cookieValidationKey: ${cookieValidationKey_logs}
    ports:
      - "9003:80"
    volumes:
      - ./public/:/var/www/html/public
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./logs/php:/var/log/php-errors.log
    restart: always

# networks:
#   default:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.28.1.0/16