version: "3.8"
services:
  nginx:
    image: nginx:1.23.1
    ports:
      - target: 80
        published: 83
        protocol: tcp
    configs:
    - source: nginx_conf
      target: /etc/nginx/nginx.conf
    - source: default_nginx
      target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: volume
        source: logs_public
        target: /var/www/html
      # - type: volume
      #   source: sirias_logs
      #   target: /var/log/nginx
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.logs.rule=Host(`logs.snhrs.ru`)"
        - "traefik.http.services.logs.loadbalancer.server.port=80" 
        - "traefik.http.services.logs.loadbalancer.sticky=true"
        - "traefik.http.services.logs.loadbalancer.sticky.cookie.name=logs"
        - "traefik.http.routers.logs.entrypoints=web"
        - "traefik.docker.network=traefik-public"

  php-fpm:
    image: ilfatgub/php-fpm:7.2_ldap
    environment:
      TZ: "Asia/Yekaterinburg"
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_IP: ${SQL_IP}
      cookieValidationKey: ${cookieValidationKey_logs}
    configs:
      - source: php_ini
        target: /usr/local/etc/php/conf.d/custom.ini
    volumes:
      - type: volume
        source: logs_public
        target: /var/www/html
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure
configs:
  default_nginx:
    external: true
  nginx_conf:
    external: true
  php_ini:
    external: true

volumes:
  logs_public:
    driver_opts:
      type: nfs
      o: addr=172.17.82.26,rw,nolock
      device: ":/var/www/html/logs.nhrs.ru"
  # sirias_logs:
  #   driver_opts:
  #     type: nfs
  #     o: addr=172.17.82.26,rw,nolock
  #     device: ":/var/www/html/logs.nhrs.ru/logs/nginx"
networks:
  traefik-public:
    external: true